<?php

namespace Modules\Uploader\Models;

use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Uploader\Enums\DiskType;
use Modules\Uploader\Service\UploaderService;

#[Fillable(['original_name', 'title', 'path', 'sizes', 'mime_type', 'disk'])]
class UploadFile extends Model
{
    use HasUlids;

    public $incrementing = false;
    protected $keyType = 'string';
    public function models()
    {
        return $this->morphedByMany(Model::class, 'model' , 'upload_files_models' ,'model_id')->withPivot(['name']);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function ($model) {

            $diskType= DiskType::tryFrom($model->disk);
            (new UploaderService($diskType))->removeFromDisk($model->path);
        });


    }
}
